In [1]:
import numpy as np
import pandas as pd

In [15]:
mem= [0,2]

In [16]:
a = np.array([1, 2, 2, 2, 3, 3, 4, 5, 6]).reshape(3,3)

In [22]:
place = np.where(a[1:, mem]==2)

In [23]:
place

(array([0], dtype=int64), array([0], dtype=int64))

In [24]:
place[0]

array([0], dtype=int64)

In [26]:
place[1]

array([0], dtype=int64)

In [27]:
import pandas as pd

In [32]:
b= pd.DataFrame(a)

In [36]:
c= b.loc[:1,:].values

In [37]:
c[0,1]

2

In [38]:
np.array([1, 2,
          3, 4])

array([1, 2, 3, 4])

In [39]:
np.ones(shape=(2,4,1))

array([[[1.],
        [1.],
        [1.],
        [1.]],

       [[1.],
        [1.],
        [1.],
        [1.]]])

In [40]:
int(3/2)

1

In [41]:
3%2

1

In [42]:
for j in range(4):
    print(j)

0
1
2
3


In [43]:
import gym

In [46]:
gym.spaces.Dict

gym.spaces.dict.Dict

In [47]:
a

array([[1, 2, 2],
       [2, 3, 3],
       [4, 5, 6]])

In [48]:
a= a[:,1]

In [51]:
a[0:2]

array([2, 3])

In [52]:
a= [1, 2, 3,4,5,6,7,8]

In [53]:
for i in range(2):
    print(a[i*4:4+i*4])
    print('-------------')

[1, 2, 3, 4]
-------------
[5, 6, 7, 8]
-------------


In [61]:
a = np.array([1.1, 2.6, 3.1, 7.9])

In [62]:
a = np.round(a).astype(int)

In [63]:
a

array([1, 3, 3, 8])

In [20]:
data = pd.read_csv('./data/requests.csv')

In [21]:
data.head(5)

Unnamed: 0  Requested File  Lifetime
0           0               6        10
1           1               1         5
2           2               1         5
3           3              16        10
4           4              16        10

In [16]:
data = data.drop(columns=['Unnamed: 0'])

In [17]:
data.head(5)

Requested File  Lifetime
0               6        10
1               1         5
2               1         5
3              16        10
4              16        10

In [19]:
data.to_csv('./data/requests.csv')

In [18]:
pwd

'C:\\Users\\arina\\Desktop\\temp'

In [8]:
temp= data.head(5)

In [9]:
temp.values

array([[ 6, 10],
       [ 1,  5],
       [ 1,  5],
       [16, 10],
       [16, 10]], dtype=int64)

In [2]:
mem_status= np.array([[2, 1, 5, 12, 1, 2], [1, 1, 5, 2, 1, 17], [2, 2, 17, 12, 2, 5], [2, 3, 17, 3, 3, 10], [12, 4, 9, 11, 4, 7], [6,5,3,10,5,8], [2, 2, 17, 12, 2, 5], [2, 3, 17, 3, 3, 10], [12, 4, 9, 11, 4, 7], [2, 3, 17, 3, 3, 10], [12, 4, 9, 11, 4, 7], [6,5,3,10,5,8], [2, 2, 17, 12, 2, 5] ])
mem_status = mem_status.reshape(13, 6)

In [6]:
mem_status

array([[14,  1,  5, 12,  1,  2],
       [ 1,  1,  5,  2,  1, 17],
       [ 2,  2, 17, 12,  2,  5],
       [ 2,  3, 17,  3,  3, 10],
       [12,  4,  9, 11,  4,  7],
       [ 6,  5,  3, 10,  5,  8],
       [ 2,  2, 17, 12,  2,  5],
       [ 2,  3, 17,  3,  3, 10],
       [12,  4,  9, 11,  4,  7],
       [ 2,  3, 17,  3,  3, 10],
       [12,  4,  9, 11,  4,  7],
       [ 6,  5,  3, 10,  5,  8],
       [ 2,  2, 17, 12,  2,  5]])

In [5]:
mem_status[0,0] = 14

In [4]:
request= np.array([[6, 5],[10, 2]])
request= request.reshape(2,2)
request

array([[ 6,  5],
       [10,  2]])

In [5]:
reward=0
current_step = 1
mem_slots= [0, 3]
MIN_COMMUN= -1
MID_COMMUN = -2

In [9]:
i=0
edge1_has = np.where(mem_status[1:4, mem_slots] == request[i,0])
edge2_has = np.where(mem_status[4:7, mem_slots] == request[i,0])
parent_has = np.where(mem_status[7:,mem_slots] == request[i,0])
if edge1_has[0].shape != (0,) and i==0:
    reward += MIN_COMMUN
    fresh= current_step - mem_status[edge1_has[0][0]+1,edge1_has[1][0]+1]
    fresh /= mem_status[edge1_has[0][0]+1,edge1_has[1][0]+2]
    reward -= fresh
    print('the item is in the row:' + str(edge1_has[0][0]+1) + '    and coloumn:' + str(edge1_has[1][0]*3) )
elif edge2_has[0].shape != (0,) and i==1:
    reward += MID_COMMUN
    fresh= current_step - mem_status[edge2_has[0][0]+4,edge2_has[1][0]+1]
    fresh /= mem_status[edge2_has[0][0]+4,edge2_has[1][0]+2]
    reward -= fresh
    print('the item is in the row:' + str(edge2_has[0][0]+4) + '    and coloumn:' + str(edge2_has[1][0]*3) )
elif parent_has[0].shape != (0,):
    reward += MID_COMMUN
    fresh= current_step - mem_status[parent_has[0][0]+7,parent_has[1][0]+1]
    fresh /= mem_status[parent_has[0][0]+7,parent_has[1][0]+2]
    print('the item is in the row:' + str(parent_has[0][0]+7) + '   and coloumn:' + str(parent_has[1][0]*3) )
    reward -= fresh

the item is in the row:11   and coloumn:0


In [13]:
edge2_has[0][0]

1

In [17]:
import numpy as np
x= np.array([range(10), range(10), range(10,20)]).reshape(10,3)

In [8]:
x[0:7] = np.roll(x[0:7],1)

In [18]:
x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9,  0,  1],
       [ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10],
       [11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [10]:
lru_table = np.zeros(shape=(18,))

In [12]:
lru_table.shape

(18,)

In [19]:
temp = x[:, [0,2]]

In [20]:
temp

array([[ 0,  2],
       [ 3,  5],
       [ 6,  8],
       [ 9,  1],
       [ 2,  4],
       [ 5,  7],
       [ 8, 10],
       [11, 13],
       [14, 16],
       [17, 19]])

In [22]:
temp2= np.zeros(shape=(10,2))
temp2[5,0]=101
temp2[9,1]=103
temp2

array([[  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [101.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0.,   0.],
       [  0., 103.]])

In [23]:
expire = temp2>temp

In [24]:
expire

array([[False, False],
       [False, False],
       [False, False],
       [False, False],
       [False, False],
       [ True, False],
       [False, False],
       [False, False],
       [False, False],
       [False,  True]])

In [2]:
import numpy as np

In [47]:
x= np.array(range(10))

In [48]:
np.random.shuffle(x)

In [49]:
print(x)

[1 9 3 8 0 5 4 2 6 7]


In [3]:
edge1 = np.array([0, 1, 2, 3, 4, 5])

In [51]:
temp = x
for num in edge1:
    temp = np.delete(temp, np.where(temp== num))

In [52]:
temp

array([9, 8, 6, 7])

In [54]:
(14 % 2 ) *3

0

In [4]:
edge1 = np.roll(edge1, 1)

In [5]:
edge1

array([5, 0, 1, 2, 3, 4])

In [6]:
a= np.array([16, 17, 0, 1, 2, 3, 4, 5])
rank = np.where(a==1)

In [12]:
a[:rank[0][0]+1] = np.roll(a[:rank[0][0]+1], 1)

In [13]:
a

array([ 1, 16, 17,  0,  2,  3,  4,  5])

In [14]:
b= np.array([16, 0, 4])

In [15]:
temp =a
for num in b:
    temp = np.delete(temp, np.where(temp==num))
print(temp)

[ 1 17  2  3  5]


In [17]:
np.zeros(shape=(2,4,2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [18]:
b = np.array([False, False, False])

In [19]:
b

array([False, False, False])

In [19]:
temp = np.random.randint(6, size=36)

In [20]:
temp= temp.reshape(6,6)
temp

array([[4, 3, 2, 4, 0, 5],
       [4, 1, 2, 3, 3, 2],
       [1, 2, 5, 5, 0, 2],
       [3, 3, 2, 5, 3, 2],
       [2, 2, 1, 4, 1, 4],
       [4, 3, 5, 1, 1, 3]])

In [21]:
mem= [0,2,4]
e1 = np.where(temp[mem, :] >= 4)

In [22]:
e1[0]

array([0, 0, 0, 1, 1, 2, 2], dtype=int64)

In [23]:
e1[1]

array([0, 3, 5, 2, 3, 3, 5], dtype=int64)

In [24]:
temp

array([[4, 3, 2, 4, 0, 5],
       [4, 1, 2, 3, 3, 2],
       [1, 2, 5, 5, 0, 2],
       [3, 3, 2, 5, 3, 2],
       [2, 2, 1, 4, 1, 4],
       [4, 3, 5, 1, 1, 3]])

In [25]:
temp[e1[0]*2, e1[1]] = 888

In [26]:
temp

array([[888,   3,   2, 888,   0, 888],
       [  4,   1,   2,   3,   3,   2],
       [  1,   2, 888, 888,   0,   2],
       [  3,   3,   2,   5,   3,   2],
       [  2,   2,   1, 888,   1, 888],
       [  4,   3,   5,   1,   1,   3]])

In [27]:
temp[0,-1]= 999

temp

In [61]:
e1 = np.where(temp[0,:]== 999)

In [37]:
e1[0]

array([0, 3], dtype=int64)

In [38]:
e1[0][-1]

3

In [39]:
temp[1,:]=2

In [41]:
(1000 - temp[0,:])

array([ 112,  997,  998,  112, 1000,    1])

In [44]:
a = (1000 - temp[0,:])
b = temp[2,:]

In [53]:
c = np.divide(a, b, where=b!=0).astype(np.float16)

In [46]:
np.zeros_like(a)

array([0, 0, 0, 0, 0, 0])

In [47]:
a.info

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [54]:
c

array([1.120e+02, 4.985e+02, 1.124e+00, 1.261e-01, 0.000e+00, 5.000e-01],
      dtype=float16)

In [55]:
c[0]

112.0

In [56]:
temp[0,-1]

999

In [57]:
temp

array([[888,   3,   2, 888,   0, 999],
       [  2,   2,   2,   2,   2,   2],
       [  1,   2, 888, 888,   0,   2],
       [  3,   3,   2,   5,   3,   2],
       [  2,   2,   1, 888,   1, 888],
       [  4,   3,   5,   1,   1,   3]])

In [62]:
e1[0].shape

(1,)

In [63]:
temp

array([[888,   3,   2, 888,   0, 999],
       [  2,   2,   2,   2,   2,   2],
       [  1,   2, 888, 888,   0,   2],
       [  3,   3,   2,   5,   3,   2],
       [  2,   2,   1, 888,   1, 888],
       [  4,   3,   5,   1,   1,   3]])

In [64]:
temp[1,:]=[1,2,3,4,5,6]

In [65]:
temp

array([[888,   3,   2, 888,   0, 999],
       [  1,   2,   3,   4,   5,   6],
       [  1,   2, 888, 888,   0,   2],
       [  3,   3,   2,   5,   3,   2],
       [  2,   2,   1, 888,   1, 888],
       [  4,   3,   5,   1,   1,   3]])

In [82]:
temp[0:2, :] = np.roll(temp[0:2, :], 1, axis=1)

In [83]:
temp

array([[  6, 888,   3,   2,   4,   5],
       [  2,   3, 888,   0, 999,   1],
       [  1,   2, 888, 888,   0,   2],
       [  3,   3,   2,   5,   3,   2],
       [  2,   2,   1, 888,   1, 888],
       [  4,   3,   5,   1,   1,   3]])

In [81]:
temp

array([[888,   3,   2,   4,   5,   6],
       [  3, 888,   0, 999,   1,   2],
       [  1,   2, 888, 888,   0,   2],
       [  3,   3,   2,   5,   3,   2],
       [  2,   2,   1, 888,   1, 888],
       [  4,   3,   5,   1,   1,   3]])

In [85]:
e1[0]

array([5], dtype=int64)